#!/usr/bin/env ruby

require 'mrdialog'


def read_makefile()
    vars = {}
    vars["BOOT_DISK"] ||= "ide0"
    vars["BOOT_MODULES"] ||= "disk_ide fs_tfs video_vga_mono bus_ps2 keyboard_ps2 mouse_ps2"
    vars["DISK_MODULES"] ||= "disk_ide"
    vars["VIDEO_MODULES"] ||= "video_vga_mono"
    vars["KEYBOARD_MODULES"] ||= "keyboard_ps2"
    vars["MOUSE_MODULES"] ||= "mouse_ps2"
    vars["NETWORK_MODULES"] ||= ""
    vars["IO_MODULES"] ||= ""
    vars["FS_MODULES"] ||= "fs_tfs"
    vars["BUS_MODULES"] ||= "bus_ps2"
    vars["INIT_MODULES"] ||= ""
    vars["KERNEL_DEBUG_MODE"] ||= "YES"
    vars["KERNEL_MODULES_MAX"] ||= "128"
    vars["KERNEL_TIMER_HANDLERS_MAX"] ||= "128"
    File.foreach("config.mk") do |line|
        if line =~ /^(\w+)\s*[:=]\s*(.*)$/
            vars[$1.strip] =  $2.strip.gsub(/#.*$/, '').strip
        end
    end
    return vars
rescue => e
    return vars
end

def write_makefile(vars)
    contents = "# DO NOT EDIT. Automatically generated by the 'make config'\n"
    count = 0
    ["DISK_MODULES", "VIDEO_MODULES", "KEYBOARD_MODULES", "IO_MODULES", "BUS_MODULES"].each do |mod_list|
        vars[mod_list].split(' ').each do |mod|
            if mod != ""
                count += 1
            end
        end
    end
    vars["KERNEL_MODULES_MAX"] = "#{count + 16}"
    modules = ""
    ["DISK_MODULES", "VIDEO_MODULES", "KEYBOARD_MODULES", "IO_MODULES", "BUS_MODULES"].each do |mod_list|
        vars[mod_list].split(' ').each do |mod|
            if mod != "" && !vars["BOOT_MODULES"].split(' ').include?(mod)
                if vars["INIT_MODULES"].split(' ').include?(mod)
                    modules += "#{mod} "
                end
            end
        end
    end
    vars["INIT_MODULES"] = modules
    vars.each do |name, value|
        contents += "#{name} = #{value}\n"
    end
    File.write("config.mk", contents);
    contents = "// DO NOT EDIT. Automatically generated by the 'make config'\n"
    if vars["KERNEL_DEBUG_MODE"] == "YES" 
        contents += "#define DEBUG\n"
    end
    contents += "#define MODULES_MAX #{vars["KERNEL_MODULES_MAX"]}\n"
    contents += "#define TIMER_HANDLERS_MAX #{vars["KERNEL_TIMER_HANDLERS_MAX"]}\n"
    File.write("config.h", contents)
    contents = "# DO NOT EDIT. Automatically generated by the 'make config'\n"
    vars["INIT_MODULES"].split(' ').each do |mod|
        contents += "#{mod}\n"
    end
    File.write("config.mod", contents)
end

def menu_boot_dev()
    dialog = MRDialog.new
    dialog.clear = true
    dialog.title = "Boot Device Configuration"

    vars = read_makefile()
    
    items = []
    items.push(["Boot Disk Name..:", 1,1,vars.key?("BOOT_DISK") ? vars["BOOT_DISK"] : "",1,20,20,0])
    result_hash = dialog.form("", items, 0, 0, 0)
    if result_hash
        result_hash.each do |key, val|
            case key
            when "Boot Disk Name..:"
                vars["BOOT_DISK"] = val
            end
        end
        write_makefile(vars)
    end
end

def menu_select_modules(title, prefix, var_name)
    dialog = MRDialog.new
    dialog.clear = true
    dialog.title = title
    dialog.dialog_options = "--separator '|' --single-quoted"

    vars = read_makefile();

    items = []
    Dir.entries("kernel/modules").each do |entry|
        unless entry == "." || entry == ".." || !entry.start_with?(prefix)
            items.push([entry.delete_prefix(prefix).delete_suffix(".c"), entry, vars[var_name].split(' ').include?(entry.delete_suffix(".c"))])
        end
    end
    selected_items = dialog.checklist("", items)

    if selected_items
        modules = ""
        selected_items.join().split('|').each do |item|
            unless item.empty?
                modules += "#{prefix}#{item.gsub(/\'/, '')} "
            end
        end
        vars[var_name] = modules
        write_makefile(vars);
    end

rescue => e
    vars[var_name] = ""
    write_makefile(vars);
end


def menu_select_boot_modules()
    dialog = MRDialog.new
    dialog.clear = true
    dialog.title = "Boot Modules"
    dialog.dialog_options = "--separator '|' --single-quoted"

    vars = read_makefile();

    items = []
    ["DISK_MODULES", "VIDEO_MODULES", "KEYBOARD_MODULES", "IO_MODULES", "BUS_MODULES"].each do |mod_list|
        vars[mod_list].split(' ').each do |mod|
            if mod != ""
                items.push([mod, "",vars["BOOT_MODULES"].split(' ').include?(mod)])
            end
        end
    end
    selected_items = dialog.checklist("Select the modules that are necessary to access the main disk:", items)

    if selected_items
        modules = ""
        selected_items.join().split('|').each do |item|
            unless item.empty?
                modules += "#{item.gsub(/\'/, '')} "
            end
        end
        vars["BOOT_MODULES"] = modules
        write_makefile(vars);
    end

rescue => e
    vars["BOOT_MODULES"] = ""
    write_makefile(vars);
end

def menu_select_init_modules()
    dialog = MRDialog.new
    dialog.clear = true
    dialog.title = "Modules loaded by default"
    dialog.dialog_options = "--separator '|' --single-quoted"

    vars = read_makefile();

    items = []
    ["DISK_MODULES", "VIDEO_MODULES", "KEYBOARD_MODULES", "IO_MODULES", "BUS_MODULES"].each do |mod_list|
        vars[mod_list].split(' ').each do |mod|
            if mod != "" && !vars["BOOT_MODULES"].split(' ').include?(mod)
                items.push([mod, "",vars["INIT_MODULES"].split(' ').include?(mod)])
            end
        end
    end
    selected_items = dialog.checklist("Select the modules that should be initialized like this after successfully accessing the disk:", items)

    if selected_items
        modules = ""
        selected_items.join().split('|').each do |item|
            unless item.empty?
                modules += "#{item.gsub(/\'/, '')} "
            end
        end
        vars["INIT_MODULES"] = modules
        write_makefile(vars);
    end

rescue => e
    puts e
    exit 1
    vars["INIT_MODULES"] = ""
    write_makefile(vars);
end

begin
    while(true)

        dialog = MRDialog.new
        dialog.clear = true
        dialog.title = "Tangerine System Software Configurator"

        vars = read_makefile();

        items = []
        items.push(["0", "Help"])
        items.push(["1", "Boot Device"])
        items.push(["2", "Boot Modules"])
        items.push(["3", "Modules loaded by default"])
        items.push(["4", "Disk Controllers"])
        items.push(["5", "I/O Controllers"])
        items.push(["6", "Video Controllers"])
        items.push(["7", "Bus Controllers"])
        items.push(["8", "Keyboard Controllers"])
        items.push(["9", "Mouse Controllers"])
        items.push(["A", "Network Controllers"])
        items.push(["B", "File System"])
        items.push(["C", "Kernel Debug Mode [#{vars["KERNEL_DEBUG_MODE"]}]"])
        items.push(["X", "Exit"])

        selected_item = dialog.menu("", items, 17, 0, 4)

        case selected_item
        when "0"
            dialog.msgbox("For the system to be bootable you need to configure the following steps:\n- Define the Controllers that will be available for utilization, in the menus of each of the types of controllers.\n- Set the controller modules that will be loaded immediately when starting the core in the boot module selection menu.\n- Define the modules that will be loaded in the second startup step, using the menu of 'Modules loaded by default'. (no need to mark all available modules, it is only necessary to mark the essential ones for the basic operation of the system)",0,0)
        when "1"
            menu_boot_dev()
        when "2"
            menu_select_boot_modules()
        when "3"
            menu_select_init_modules()
        when "4"
            menu_select_modules("Disk Controllers", "disk_", "DISK_MODULES")
        when "5"
            menu_select_modules("I/O Controllers", "io_", "IO_MODULES")
        when "6"
            menu_select_modules("Video Controllers", "video_", "VIDEO_MODULES")
        when "7"
            menu_select_modules("Bus Controllers", "bus_", "BUS_MODULES")
        when "8"
            menu_select_modules("Keyboard Controllers", "keyboard_", "KEYBOARD_MODULES")
        when "9"
            menu_select_modules("Mouse Controllers", "mouse_", "MOUSE_MODULES")
        when "A"
            menu_select_modules("Network Controllers", "network_", "NETWORK_MODULES")
        when "B"
            menu_select_modules("File System", "fs_", "FS_MODULES")
        when "C"
            vars["KERNEL_DEBUG_MODE"] = vars["KERNEL_DEBUG_MODE"] == "YES" ? "NO" : "YES"
            write_makefile(vars)
        else
            write_makefile(read_makefile())
            system("clear")
            return
        end
    end
rescue => e
    system("clear")
end